version: "3.8"
services:
    web:
        build: .
        container_name: where-to-stay
        ports:
            - "3000:3000"
        environment:
            - HERE_API_KEY=${HERE_API_KEY}
            - PORT=3000
            - DEFAULT_SIZE_VALUE=20
            - MAX_SIZE_VALUE=50
            - MIN_SIZE_VALUE=10
            - DEFAULT_PAGE=1
            - MIN_PAGE_VALUE=1
        depends_on:
            - db
            - redis
        links:
            - db
            - redis
    redis:
        image: redis
        container_name: where-to-stay-redis
        expose:
            - 6379
    db:
        container_name: where-to-stay-mongo
        image: 'mongo:4'
        ports:
            - '27017:27017'
        volumes:
            - ./data/db:/data/db
